package umich.hijack.core;

public enum HiJackIOCommand {
	SET_INPUT,
	SET_OUTPUT,
	ANALOG_READ,
	ANALOG_WRITE,
	DIGITAL_READ,
	DIGITAL_WRITE,
	DISABLE_INTERRUPT,
	ENABLE_INTERRUPT_RISING,
	ENABLE_INTERRUPT_FALLING
}
